ssl:
  validate_ssl: true

credentials:
  user: ''
  password: ''

formats:
  datetime_format: '%Y-%m-%d %H:%M:%S'

periods:
  # Default peak periods as defined by HQ (as of winter 2021-2022)
  morning_peak_start: "06:00:00"
  morning_peak_end: "09:00:00"
  evening_peak_start: "16:00:00"
  evening_peak_end: "20:00:00"

  # Offset in hours to apply to the peak period start time to find the start of the anchor period
  # Per HQ documentation (as of winter 2021-2022) it is 5 hours before the next peak
  anchor_start_offset: 5
  
  # Duration of the anchor period
  # Per HQ documentation (as of winter 2021-2022) it is a duration of 3 hours
  anchor_duration: 3 
  
  # Data will be refreshed after 5mn (avoid killing hydro api)
  event_refresh_seconds: 300
  
  # Pre-heat offset
  # Will not be calculated if pre_heat_start_offset = 0
  pre_heat_start_offset: 3
  pre_heat_end_offset: 0
  
mqtt:
  server: ''
  port: 1883
  user: ''
  password: ''
  # mqtt topic will be {base_topic}/{contract_id}/(next|state|reference_period)/#
  base_topic: 'hydroqc'